apiVersion: v1
kind: Service
metadata:
    name: "studioghibli-dea6"
    labels:
        app: "studioghibli-dea6"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "studioghibli-dea6"