name: React Image
on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
      branch:
        description: Branch to trigger build on
        default: main
        required: true
        type: choice
        options:
        - develop
        - main
jobs:
  build:
    runs-on: ubantu-latest
    name: build react image 
    defaults:
      run:
        working-directory: Group1_GhiblisMovie
    
    steps:
    - name: setup Node.js environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 18.11.0
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install react package
      run: npm ci
    
