on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: AWS ECR push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAXOUG4SD3ZUMM7CMI
        aws-secret-access-key: 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 
        aws-region: us-east-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 512457740535.dkr.ecr.us-east-1.amazonaws.com/group1 
        ECR_REPOSITORY: 512457740535.dkr.ecr.us-east-1.amazonaws.com/group1 
        IMAGE_TAG: latest
      run: |
        # Build a docker container and push it to ECR
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo “Pushing image to ECR...”
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo “::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG”
